### ISSUE TITLE
Upstream Teensy 3.1 Support

### ISSUE THREAD

**Issue by gregory-nutt** [jodersky/nuttx#1]
Hi, Jakob,

I want let you know that I have added support for the Teensy 3.1 to the upstream NuttX repository.  The code there is different but leverages many of the changes and settings that you have here.  Thanks for making this available... you made my job a lot easier.

Greg

**Comment by jodersky** [comment]
Hi Greg,
awesome! I was planning to tell you about my k20 fork once the code was in better shape, however development was pretty slow on my side.
Thanks for the notification.

--Jakob.

**Comment by jodersky** [comment]
By the way,
I made some more changes to Kinetis K20 code on master of https://github.com/jodersky/px4-nuttx

**Comment by gregory-nutt** [comment]
Thanks for the tip.  I think I have everything from that repository too.  I might have missed something because it is hard sort through all of the changes.  But don't think so.
